<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="zhouwenqiudeMacBook-Pro.local" failures="4" tests="4" name="test1" time="0.061" errors="0" timestamp="2021-10-13T19:50:41 EDT">
  <testcase classname="testsuite.Test_Cacultor" name="test_add" time="0.006">
    <failure type="java.lang.AssertionError" message="加法 did not expect to find [3.0] but found [2.0]">
      <![CDATA[java.lang.AssertionError: 加法 did not expect to find [3.0] but found [2.0]
at testsuite.Test_Cacultor.test_add(Test_Cacultor.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at RunTestNGProgrammatically.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:38)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_add -->
  <testcase classname="testsuite.Test_Cacultor" name="test_add" time="0.0">
    <failure type="java.lang.AssertionError" message="加法 did not expect to find [5.0] but found [4.0]">
      <![CDATA[java.lang.AssertionError: 加法 did not expect to find [5.0] but found [4.0]
at testsuite.Test_Cacultor.test_add(Test_Cacultor.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at RunTestNGProgrammatically.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:38)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_add -->
  <testcase classname="testsuite.Test_Cacultor" name="test_minus" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testsuite.Test_Cacultor.test_minus(Test_Cacultor.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at RunTestNGProgrammatically.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:38)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_minus -->
  <testcase classname="testsuite.Test_Cacultor" name="test_minus" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testsuite.Test_Cacultor.test_minus(Test_Cacultor.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at RunTestNGProgrammatically.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:38)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_minus -->
</testsuite> <!-- test1 -->
