<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="zhouwenqiudeMacBook-Pro.local" failures="9" tests="9" name="test1" time="0.08" errors="0" timestamp="2021-10-24T21:59:52 EDT">
  <testcase classname="package_test_2.Test_Cry" name="testSingleString" time="0.0">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;first-name&amp;apos; is required by @Test on method testSingleString but has not been marked @Optional or defined
">
      <![CDATA[org.testng.TestNGException: 
Parameter 'first-name' is required by @Test on method testSingleString but has not been marked @Optional or defined

at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testSingleString -->
  <testcase classname="package_test_2.Test_Cry" name="test_cry1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at package_test_2.Test_Cry.test_cry1(Test_Cry.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_cry1 -->
  <testcase classname="package_test_2.Test_Cry" name="test_cry1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at package_test_2.Test_Cry.test_cry1(Test_Cry.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_cry1 -->
  <testcase classname="package_test_2.Test_Cry" name="test_cry2" time="0.004">
    <failure type="java.lang.AssertionError" message="加法 did not expect to find [3.0] but found [2.0]">
      <![CDATA[java.lang.AssertionError: 加法 did not expect to find [3.0] but found [2.0]
at package_test_2.Test_Cry.test_cry2(Test_Cry.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_cry2 -->
  <testcase classname="package_test_2.Test_Cry" name="test_cry2" time="0.0">
    <failure type="java.lang.AssertionError" message="加法 did not expect to find [5.0] but found [4.0]">
      <![CDATA[java.lang.AssertionError: 加法 did not expect to find [5.0] but found [4.0]
at package_test_2.Test_Cry.test_cry2(Test_Cry.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_cry2 -->
  <testcase classname="testsuite.Test_Cacultor" name="test_add" time="0.0">
    <failure type="java.lang.AssertionError" message="加法 did not expect to find [3.0] but found [2.0]">
      <![CDATA[java.lang.AssertionError: 加法 did not expect to find [3.0] but found [2.0]
at testsuite.Test_Cacultor.test_add(Test_Cacultor.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_add -->
  <testcase classname="testsuite.Test_Cacultor" name="test_add" time="0.0">
    <failure type="java.lang.AssertionError" message="加法 did not expect to find [5.0] but found [4.0]">
      <![CDATA[java.lang.AssertionError: 加法 did not expect to find [5.0] but found [4.0]
at testsuite.Test_Cacultor.test_add(Test_Cacultor.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_add -->
  <testcase classname="testsuite.Test_Cacultor" name="test_minus" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testsuite.Test_Cacultor.test_minus(Test_Cacultor.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_minus -->
  <testcase classname="testsuite.Test_Cacultor" name="test_minus" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testsuite.Test_Cacultor.test_minus(Test_Cacultor.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at utils.TestNgXmlUsingCode.testNgXmlSuite(TestNgXmlUsingCode.java:33)
at TestEntrance.TestApp.main(TestApp.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_minus -->
</testsuite> <!-- test1 -->
